name: terraform_linting
on: [push]
jobs:
  terraform:
    name: terraform CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main